name: CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sellezzzzz
          password: dckr_pat_GMx_2yHv51ybIN2iVDCJASq5Xpg

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sellezzzzz/clockbox:latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0

